#Bank management system
"""
account has - name, age, email, accNo, ifsc code, branch, pin
functions:
- createAccount
- deposit
- withdraw
- viewBalance
- viewDetails
- updateDetails
- delete
accNo, ifsc - can't be given by user, must be generated by the system
"""
import json
import random
import string
from pathlib import Path

class Bank:

    data = []
    database = 'data.json'

    try:
        if Path(database).exists():
            with open(database) as f:
                data = json.loads(f.read())
        else:
            print('No such file exists')
    except Exception as e:
            print(f'An error occurred as {e}')

    @classmethod
    def __update(cls):
        with open(Bank.database,'w') as f:
            f.write(json.dumps(cls.data))

    @classmethod
    def __generateAccNo(cls):
        while True:
            alpha = random.choices(string.ascii_letters, k=3)
            digits = random.choices(string.digits, k=3)
            sp = random.choices('!@#$%^&*', k=2)
            new_id = alpha + digits + sp
            random.shuffle(new_id)
            accNo = "".join(new_id)
            exists = any(accNo == user['accNo'] for user in Bank.data)
            if not exists:
                return accNo

    def createAccount(self):
        info = {
            'name': input('Enter your Name (first name, middle name, last name): )'),
            'age': int(input('Enter your age: ') or 0),
            'email': input('Enter your email: '),
            'accNo': Bank.__generateAccNo(),
            'branch': input('Enter your branch: '),
            'pin': int(input('Enter a 4-digit pin: ')),
            'balance': 0
        }
        if info['age']<16:
            print('Account cannot be created! Age must be greater than 16')
            return

        if len(str(info['pin'])) != 4:
            print('Account cannot be created! Pin must be of 4-digits')
            return

        if info['name'] == '' or info['age'] <= 0 or info['email'] == '' or info['branch'] == '':
            print('Account cannot be created! Check your details')
            return

        else:
            print('Account successfully created!')
            for i in info:
                print(f'{i}: {info[i]}')
            print('Please check your details')
            Bank.data.append(info)
            Bank.__update()

    def deposit(self):
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin), None)
        if not userData:
            print('Account not found!')
            return

        amt = int(input('Enter your amount: '))
        if amt>10000 or amt<=0:
            print('Account cannot be deposited')
            return
        else:
            userData['balance'] += amt
            Bank.__update()
            print('Account successfully deposited!')
            print(f'Updated balance: {userData['balance']}')

    def withdraw(self):
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin),None)
        if not userData:
            print('Account not found!')
            return
        amt = int(input('Enter amount you want to withdraw:'))
        if amt>=userData['balance'] or amt<=0:
            print('Insufficient balance')
            return
        userData['balance'] -= amt
        Bank.__update()
        print('Account successfully withdrawn!')
        print(f'Updated balance: {userData['balance']}')

    def getBalance(self):
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin), None)
        if not userData:
            print('Account not found!')
            return
        print(f'Account balance: {userData['balance']}')

    def viewDetails(self):
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin), None)
        if not userData:
            print('Account not found!')
            return
        for i in userData:
            print(f'{i}: {userData[i]}')


    def updateDetails(self):
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin), None)
        print('What do you want to update?')
        print('1. Name')
        print('2. Email')
        print('3. Branch')
        print('4. Pin')
        choice = int(input('Enter your choice:'))
        if choice == 1:
            userData['name'] = input('Enter your name: ')
            Bank.__update()
            print('Account successfully updated!')
            print(f'Updated name: {userData['name']}')
            return
        if choice == 2:
            userData['email'] = input('Enter your email: ')
            Bank.__update()
            print('Account successfully updated!')
            print(f'Updated email: {userData["email"]}')
            return
        if choice == 3:
            userData['branch'] = input('Enter your branch: ')
            Bank.__update()
            print('Account successfully updated!')
            print(f'Updated branch: {userData["branch"]}')
            return
        if choice == 4:
            userData['pin'] = int(input('Enter your pin: '))
            Bank.__update()
            print('Account successfully updated!')
            print(f'Updated pin: {userData["pin"]}')
            return

    def delete(self):
        print('Are you sure you want to delete this account?')
        choice = input('Enter your choice (Yes/No):')
        if choice.lower() == 'no':
            print('Account not deleted!')
            return
        accNo = input('Enter your account number:')
        pin = int(input('Enter your pin:'))
        userData = next((user for user in Bank.data if user['accNo']==accNo and user['pin']==pin), None)
        if not userData:
            print('Account not found!')
            return
        idx = Bank.data.index(userData)
        Bank.data.pop(idx)
        Bank.__update()
        print('Account successfully deleted!')

user = Bank()
print('Press 1 for create account')
print('Press 2 for deposit')
print('Press 3 for withdraw')
print('Press 4 for viewBalance')
print('Press 5 for viewDetails')
print('Press 6 for updateDetails')
print('Press 7 for delete')

check = int(input('Enter your choice: '))

if check==1:
    user.createAccount()

elif check==2:
    user.deposit()

elif check==3:
    user.withdraw()

elif check==4:
    user.getBalance()

elif check==5:
    user.viewDetails()

elif check==6:
    user.updateDetails()

elif check==7:
    user.delete()